on:
  [push, pull_request]:
     branches:
      - master
      - develop

  name: Continuous integration (PR)

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: git fetch --all --tags
  
        - name: Setup nodejs
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
  
        - name: Install dependencies
          run: npm ci
  
        - name: Run Lint
          run: npm run lint
        
        - name: Run Tests
          run: npm run test
